let logo = document.createElement('img');
logo.src = 'logo.svg';
let titleElement = document.createElement('h1');
titleElement.innerText = 'Rooted in Faith';
let header = document.createElement('header');
header.appendChild(logo);
header.appendChild(titleElement);
document.body.appendChild(header);

let mainContainer = document.createElement('main');
let p1 = document.createElement('p');
let p2 = document.createElement('p');
p1.innerText = "Rooted in faith, our mission is to serve the spiritual needs of all in our community. Through our ministries and services, we strive to bring God's word and love to our lives and the lives of those around us.";
p2.innerText = "Rooted in Faith has been ministering to our community for over 100 years. We strive to provide a safe and welcoming environment for our members and guests. We believe that God has put us on this earth to love and serve one another. We invite you to join us and make a difference in your own life and the lives of others.";
mainContainer.appendChild(p1);
mainContainer.appendChild(p2);
document.body.appendChild(mainContainer);

let leftContainer = document.createElement('div');
leftContainer.className = "left-container";
let h2 = document.createElement('h2');
h2.innerText = "Our Ministries";
let ul = document.createElement('ul');
let item1 = document.createElement('li');
let item2 = document.createElement('li');
let item3 = document.createElement('li');
let item4 = document.createElement('li');
item1.innerText = "Adult Ministry";
item2.innerText = "Children's Ministry";
item3.innerText = "Youth Ministry";
item4.innerText = "Mission Trip";
ul.appendChild(item1);
ul.appendChild(item2);
ul.appendChild(item3);
ul.appendChild(item4);
leftContainer.appendChild(h2);
leftContainer.appendChild(ul);
document.body.appendChild(leftContainer);

let rightContainer = document.createElement('div');
rightContainer.className = "right-container";
let h3 = document.createElement('h2');
h3.innerText = "Our Services";
let ul2 = document.createElement('ul');
let item5 = document.createElement('li');
let item6 = document.createElement('li');
let item7 = document.createElement('li');
let item8 = document.createElement('li');
item5.innerText = "Sunday Worship";
item6.innerText = "Midweek Bible Study";
item7.innerText = "Family Events";
item8.innerText = "Weekly Devotional";
ul2.appendChild(item5);
ul2.appendChild(item6);
ul2.appendChild(item7);
ul2.appendChild(item8);
rightContainer.appendChild(h3);
rightContainer.appendChild(ul2);
document.body.appendChild(rightContainer);

let footerContainer = document.createElement('div');
footerContainer.className = "footer-container";
let h4 = document.createElement('h2');
h4.innerText = "Stay Connected";
let p3 = document.createElement('p');
p3.innerText = "Follow us on social media for updates about our ministries and services.";
footerContainer.appendChild(h4);
footerContainer.appendChild(p3);
document.body.appendChild(footerContainer);

let socialContainer = document.createElement('div');
socialContainer.className = "social-container";
let fbLink = document.createElement('a');
let twLink = document.createElement('a');
let igLink = document.createElement('a');
fbLink.href = "https://www.facebook.com/RootedinFaith";
fbLink.innerText = "Facebook";
twLink.href = "https://twitter.com/RootedinFaith";
twLink.innerText = "Twitter";
igLink.href = "https://www.instagram.com/RootedinFaith";
igLink.innerText = "Instagram";
socialContainer.appendChild(fbLink);
socialContainer.appendChild(twLink);
socialContainer.appendChild(igLink);
footerContainer.appendChild(socialContainer);
document.body.appendChild(footerContainer);